# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nro', models.CharField(max_length=5)),
                ('desc', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='C_proveedores',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_prove', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Causa_rechazo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rif', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=75)),
                ('tlf1', models.CharField(max_length=15)),
                ('tlf2', models.CharField(blank=True, max_length=15)),
                ('dire', models.CharField(max_length=200)),
                ('act_eco', models.CharField(blank=True, max_length=100)),
                ('cond_contrib', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=50)),
                ('costo_uso', models.DecimalField(decimal_places=2, max_digits=30)),
                ('cantidad', models.IntegerField()),
                ('serial', models.CharField(blank=True, max_length=50, unique=True)),
                ('f_act', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo_movimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('codigo_equ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('f_ini', models.DateField(blank=True)),
                ('f_fin', models.DateField(blank=True)),
                ('f_est', models.DateField(blank=True)),
                ('estatus', models.CharField(choices=[('n', 'No Empezada'), ('e', 'Ejecucion'), ('p', 'Problemas'), ('c', 'culminado')], max_length=1)),
                ('facturada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa_servicio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_eta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nro_factura', models.AutoField(primary_key=True, serialize=False)),
                ('nro_control', models.IntegerField(unique=True)),
                ('persona_cc', models.CharField(max_length=60)),
                ('email_cc', models.CharField(max_length=60)),
                ('cargo_cc', models.CharField(blank=True, max_length=50)),
                ('cond_pago', models.CharField(choices=[('c', 'Credito'), ('d', 'Debito'), ('e', 'Efectivo')], max_length=1)),
                ('pagada', models.BooleanField(default=False)),
                ('banco_dest', models.CharField(blank=True, max_length=50)),
                ('nro_ref', models.CharField(blank=True, max_length=100)),
                ('codigo_eta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=20)),
                ('presen', models.CharField(blank=True, max_length=50)),
                ('f_act', models.DateField(auto_now=True)),
                ('precio_act', models.DecimalField(decimal_places=4, max_digits=30)),
                ('cantidad', models.IntegerField()),
                ('serial', models.CharField(blank=True, max_length=50, unique=True)),
                ('largo', models.CharField(blank=True, max_length=20)),
                ('ancho', models.CharField(blank=True, max_length=20)),
                ('alto', models.CharField(blank=True, max_length=20)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material_movimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('codigo_mat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Material_presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=4, max_digits=30)),
                ('cantidad', models.IntegerField()),
                ('codigo_mat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('tipo', models.CharField(choices=[('i', 'Ingreso'), ('r', 'Retorno'), ('e', 'Egreso')], max_length=1)),
                ('autorizado', models.BooleanField(default=False)),
                ('f_sol', models.DateField(auto_now_add=True)),
                ('codigo_ne', models.CharField(blank=True, max_length=20)),
                ('codigo_oc', models.CharField(blank=True, max_length=20)),
                ('persona_t', models.CharField(blank=True, max_length=60)),
                ('persona_e', models.CharField(blank=True, max_length=60)),
                ('proveedor', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=50)),
                ('repuesta', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('codigo_en', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('validez_o', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('observ', models.CharField(blank=True, max_length=300)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=150)),
                ('estatus', models.CharField(choices=[('p', 'Preventa'), ('a', 'Aprobado'), ('e', 'Ejecucion'), ('c', 'culminado'), ('r', 'Rechazado')], max_length=1)),
                ('f_ini', models.DateField(blank=True)),
                ('f_fin', models.DateField(blank=True)),
                ('f_est', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_tecnico',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_t', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('a', 'Avance'), ('p', 'Problema'), ('o', 'Otro')], max_length=1)),
                ('observ', models.CharField(max_length=300)),
                ('codigo_eta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_detalle',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('persona_a', models.CharField(max_length=60)),
                ('cargo_a', models.CharField(max_length=50)),
                ('vicios_ocu', models.CharField(blank=True, max_length=500)),
                ('observ', models.CharField(max_length=500)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_inicial',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('persona_a', models.CharField(blank=True, max_length=60)),
                ('cargo_a', models.CharField(blank=True, max_length=50)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('observ', models.CharField(blank=True, max_length=500)),
                ('factibilidad', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('riesgos', models.CharField(blank=True, max_length=300)),
                ('complejidad', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('completado', models.BooleanField(default=False)),
                ('nombre_t', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
                ('precio_act', models.DecimalField(decimal_places=4, max_digits=30)),
                ('f_act', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio_presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=4, max_digits=30)),
                ('codigo_pre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Presupuesto')),
                ('codigo_ser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('disp', models.CharField(blank=True, max_length=100)),
                ('referido_p', models.CharField(blank=True, max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('ubicacion', models.CharField(max_length=150)),
                ('estatus', models.CharField(blank=True, choices=[('n', 'Nueva'), ('p', 'Procesada'), ('a', 'Atendida')], max_length=1)),
                ('nombre_cc', models.CharField(max_length=75)),
                ('tlf_cc', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
                ('cargo_cc', models.CharField(max_length=50)),
                ('rif_c', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=15)),
                ('nombre2', models.CharField(blank=True, max_length=15)),
                ('apellido1', models.CharField(max_length=15)),
                ('apellido2', models.CharField(blank=True, max_length=15)),
                ('tlf', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=20)),
                ('dire', models.CharField(max_length=50)),
                ('cargo', models.CharField(choices=[('c', 'Coordinador'), ('t', 'Tecnico'), ('a', 'Almacenista'), ('v', 'Vendedor')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto_tecnico',
            name='ci_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnico',
            name='codigo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ci_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='codigo_ri',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Reporte_inicial'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='codigo_s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Solicitud'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='ci_vendedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='codigo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ci_almace',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador'),
        ),
        migrations.AddField(
            model_name='material_presupuesto',
            name='codigo_pre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Presupuesto'),
        ),
        migrations.AddField(
            model_name='material_movimiento',
            name='codigo_mov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movimiento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='codigo_pre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Presupuesto'),
        ),
        migrations.AddField(
            model_name='etapa_servicio',
            name='codigo_ser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Servicio'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='codigo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='codigo_rd',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Reporte_detalle'),
        ),
        migrations.AddField(
            model_name='equipo_movimiento',
            name='codigo_mov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movimiento'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='codigo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='causa_rechazo',
            name='codigo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='c_proveedores',
            name='codigo_mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Material'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='codigo_eta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Etapa'),
        ),
        migrations.AlterUniqueTogether(
            name='servicio_presupuesto',
            unique_together=set([('codigo_pre', 'codigo_ser')]),
        ),
        migrations.AlterUniqueTogether(
            name='proyecto_tecnico',
            unique_together=set([('codigo_pro', 'ci_tecnico')]),
        ),
        migrations.AlterUniqueTogether(
            name='material_presupuesto',
            unique_together=set([('codigo_pre', 'codigo_mat')]),
        ),
        migrations.AlterUniqueTogether(
            name='material_movimiento',
            unique_together=set([('codigo_mov', 'codigo_mat')]),
        ),
        migrations.AlterUniqueTogether(
            name='etapa_servicio',
            unique_together=set([('codigo_ser', 'codigo_eta')]),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together=set([('codigo', 'letra')]),
        ),
        migrations.AlterUniqueTogether(
            name='equipo_movimiento',
            unique_together=set([('codigo_mov', 'codigo_equ')]),
        ),
        migrations.AlterUniqueTogether(
            name='c_proveedores',
            unique_together=set([('codigo_prove', 'codigo_mat')]),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together=set([('codigo', 'nro')]),
        ),
    ]
