# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nro', models.CharField(max_length=5)),
                ('desc', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Causa_rechazo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rif', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=75)),
                ('tlf1', models.CharField(max_length=15)),
                ('tlf2', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('dire', models.CharField(max_length=200)),
                ('act_eco', models.CharField(blank=True, max_length=100)),
                ('cond_contrib', models.CharField(blank=True, choices=[('Ordinario', 'Ordinario'), ('Especial', 'Especial'), ('Formales', 'Formales')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('f_ini', models.DateField(blank=True, null=True)),
                ('f_fin', models.DateField(blank=True, null=True)),
                ('f_est', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Ejecucion', 'Ejecucion'), ('Culminado', 'Culminado')], default='Pendiente', max_length=10)),
                ('facturada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa_tecnico_movimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nro_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('nro_control', models.IntegerField(unique=True)),
                ('f_emi', models.DateField()),
                ('f_ven', models.DateField()),
                ('persona_cc', models.CharField(max_length=100)),
                ('email_cc', models.CharField(max_length=100)),
                ('cargo_cc', models.CharField(blank=True, max_length=100)),
                ('departamento_cc', models.CharField(blank=True, max_length=100)),
                ('cond_pago', models.CharField(choices=[('Credito', 'Credito'), ('Debito', 'Debito'), ('Efectivo', 'Efectivo')], max_length=10)),
                ('pagada', models.BooleanField(default=False)),
                ('banco_dest', models.CharField(blank=True, max_length=100)),
                ('nro_ref', models.CharField(blank=True, max_length=100)),
                ('monto_total', models.DecimalField(decimal_places=4, max_digits=50)),
                ('codigo_eta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=300)),
                ('presen', models.CharField(blank=True, max_length=50)),
                ('f_act', models.DateField(auto_now=True)),
                ('precio_act', models.DecimalField(decimal_places=2, max_digits=30)),
                ('cantidad', models.IntegerField(blank=True, default=0)),
                ('serial', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('largo', models.CharField(blank=True, max_length=20)),
                ('ancho', models.CharField(blank=True, max_length=20)),
                ('alto', models.CharField(blank=True, max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material_movimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('codigo_mat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Material_presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=4, max_digits=30)),
                ('cantidad', models.IntegerField()),
                ('codigo_mat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Material_proveedor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_mat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Retorno', 'Retorno'), ('Egreso', 'Egreso')], max_length=10)),
                ('completado', models.BooleanField(default=False)),
                ('autorizado', models.BooleanField(default=False)),
                ('f_sol', models.DateField(auto_now_add=True)),
                ('codigo_ne', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_oc', models.CharField(blank=True, max_length=50, null=True)),
                ('persona_t', models.CharField(blank=True, max_length=60, null=True)),
                ('persona_e', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=150)),
                ('respuesta', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('codigo_en', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('validez_o', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('observ', models.CharField(blank=True, max_length=300)),
                ('desc', models.CharField(max_length=200)),
                ('cond_g', models.CharField(blank=True, max_length=500)),
                ('cond_p', models.CharField(blank=True, max_length=500)),
                ('atencion_n', models.CharField(max_length=75)),
                ('atencion_e', models.EmailField(max_length=254)),
                ('estatus', models.CharField(choices=[('Preventa', 'Preventa'), ('Aprobado', 'Aprobado'), ('Cerrado', 'Cerrado'), ('Rechazado', 'Rechazado')], default='Preventa', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rif', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
                ('tlf1', models.CharField(max_length=15)),
                ('tlf2', models.CharField(blank=True, max_length=15)),
                ('dire', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('ubicacion', models.CharField(max_length=150)),
                ('estatus', models.CharField(choices=[('Preventa', 'Preventa'), ('Aprobado', 'Aprobado'), ('Ejecucion', 'Ejecucion'), ('Culminado', 'Culminado'), ('Rechazado', 'Rechazado')], default='Preventa', max_length=10)),
                ('f_ini', models.DateField(blank=True, null=True)),
                ('f_fin', models.DateField(blank=True, null=True)),
                ('f_est', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_tecnico',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre_t', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('Avance', 'Avance'), ('Problema', 'Problema'), ('Otro', 'Otro')], max_length=10)),
                ('observ', models.CharField(max_length=300)),
                ('leido', models.BooleanField(default=False)),
                ('codigo_eta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_detalle',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('persona_a', models.CharField(max_length=60)),
                ('cargo_a', models.CharField(max_length=60)),
                ('nombre_t', models.CharField(max_length=60)),
                ('vicios_ocu', models.CharField(blank=True, max_length=500)),
                ('observ', models.CharField(max_length=500)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_inicial',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('persona_a', models.CharField(blank=True, max_length=60)),
                ('cargo_a', models.CharField(blank=True, max_length=60)),
                ('desc', models.CharField(blank=True, max_length=1500)),
                ('observ', models.CharField(blank=True, max_length=500)),
                ('factibilidad', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('riesgos', models.CharField(blank=True, max_length=300)),
                ('complejidad', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('completado', models.BooleanField(default=False)),
                ('nombre_t', models.CharField(blank=True, max_length=60)),
                ('f_vis', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_servicio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('codigo_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Reporte')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=200)),
                ('precio_act', models.DecimalField(decimal_places=2, max_digits=30)),
                ('f_act', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio_presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=30)),
                ('cantidad', models.IntegerField()),
                ('codigo_pre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Presupuesto')),
                ('codigo_ser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('disp', models.CharField(blank=True, max_length=100)),
                ('referido_p', models.CharField(blank=True, max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('ubicacion', models.CharField(max_length=150)),
                ('estatus', models.CharField(choices=[('Nueva', 'Nueva'), ('Procesada', 'Procesada'), ('Atendida', 'Atendida')], default='Nueva', max_length=10)),
                ('nombre_cc', models.CharField(max_length=75)),
                ('tlf_cc', models.CharField(max_length=15)),
                ('correo_cc', models.EmailField(max_length=254)),
                ('cargo_cc', models.CharField(max_length=50)),
                ('f_sol', models.DateField(auto_now_add=True)),
                ('f_vis', models.DateField(null=True)),
                ('rif_c', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=15)),
                ('nombre2', models.CharField(blank=True, max_length=15)),
                ('apellido1', models.CharField(max_length=15)),
                ('apellido2', models.CharField(blank=True, max_length=15)),
                ('tlf', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('dire', models.CharField(blank=True, max_length=200)),
                ('cargo', models.CharField(choices=[('c', 'Coordinador'), ('t', 'Tecnico'), ('a', 'Almacenista'), ('v', 'Vendedor')], max_length=1)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reporte_servicio',
            name='codigo_ser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Servicio'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnico',
            name='ci_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnico',
            name='codigo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ci_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='codigo_ri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Reporte_inicial'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='codigo_s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Solicitud'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='ci_vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='codigo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ci_almace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='rif_prove',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Proveedor'),
        ),
        migrations.AddField(
            model_name='material_proveedor',
            name='codigo_prove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proveedor'),
        ),
        migrations.AddField(
            model_name='material_presupuesto',
            name='codigo_pre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Presupuesto'),
        ),
        migrations.AddField(
            model_name='material_movimiento',
            name='codigo_mov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movimiento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='codigo_pre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Presupuesto'),
        ),
        migrations.AddField(
            model_name='etapa_tecnico_movimiento',
            name='ci_tecnico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador'),
        ),
        migrations.AddField(
            model_name='etapa_tecnico_movimiento',
            name='codigo_eta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Etapa'),
        ),
        migrations.AddField(
            model_name='etapa_tecnico_movimiento',
            name='codigo_mov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movimiento'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='codigo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='codigo_rd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Reporte_detalle'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='codigo_pro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='causa_rechazo',
            name='codigo_pro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='codigo_eta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Etapa'),
        ),
        migrations.AlterUniqueTogether(
            name='servicio_presupuesto',
            unique_together=set([('codigo_pre', 'codigo_ser')]),
        ),
        migrations.AlterUniqueTogether(
            name='reporte_servicio',
            unique_together=set([('codigo_ser', 'codigo_rep')]),
        ),
        migrations.AlterUniqueTogether(
            name='proyecto_tecnico',
            unique_together=set([('codigo_pro', 'ci_tecnico')]),
        ),
        migrations.AlterUniqueTogether(
            name='material_proveedor',
            unique_together=set([('codigo_prove', 'codigo_mat')]),
        ),
        migrations.AlterUniqueTogether(
            name='material_presupuesto',
            unique_together=set([('codigo_pre', 'codigo_mat')]),
        ),
        migrations.AlterUniqueTogether(
            name='material_movimiento',
            unique_together=set([('codigo_mov', 'codigo_mat')]),
        ),
        migrations.AlterUniqueTogether(
            name='etapa_tecnico_movimiento',
            unique_together=set([('codigo_mov', 'ci_tecnico', 'codigo_eta')]),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together=set([('codigo_pro', 'letra')]),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together=set([('codigo_eta', 'nro')]),
        ),
    ]
