# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='codigo_eta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Etapa'),
        ),
    ]
