# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170227_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_inicial',
            name='desc',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
