# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161107_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='dire',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
