# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170227_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa_rechazo',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='observ',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reporte_detalle',
            name='observ',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reporte_detalle',
            name='vicios_ocu',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reporte_inicial',
            name='desc',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='reporte_inicial',
            name='observ',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reporte_inicial',
            name='riesgos',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
