# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161107_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fax',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
