# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170227_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
