# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cliente_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cond_contrib',
            field=models.CharField(blank=True, choices=[('o', 'Ordinario'), ('e', 'Especial'), ('f', 'Formales')], max_length=10),
        ),
    ]
