# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170227_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='cond_g',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='cond_p',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='observ',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
