# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161109_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='correo',
            new_name='correo_cc',
        ),
    ]
