# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170301_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='material',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='material',
            name='largo',
        ),
    ]
