# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161115_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(choices=[('n', 'Nueva'), ('p', 'Procesada'), ('a', 'Atendida')], default='n', max_length=1),
        ),
    ]
