# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161115_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='f_sol',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
