# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170301_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='atencion_e',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='atencion_n',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='desc',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='descuento',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='validez_o',
            field=models.IntegerField(blank=True),
        ),
    ]
