# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170301_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='descuento',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='validez_o',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
