# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_solicitud_f_sol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='correo_cc',
            field=models.EmailField(max_length=254),
        ),
    ]
