# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20161117_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte_inicial',
            name='f_vis',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('p', 'Preventa'), ('a', 'Aprobado'), ('e', 'Ejecucion'), ('c', 'culminado'), ('r', 'Rechazado')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
