# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20161118_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='f_ini',
            field=models.DateField(blank=True, null=True),
        ),
    ]
