# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20161118_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='f_est',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='f_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
