# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20161118_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codigo_ri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Reporte_inicial'),
        ),
    ]
