# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20161119_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio_act',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
