# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20161119_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
