# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20161119_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('Preventa', 'Preventa'), ('Aprobado', 'Aprobado'), ('Ejecucion', 'Ejecucion'), ('Culminado', 'Culminado'), ('Rechazado', 'Rechazado')], default='p', max_length=1),
        ),
    ]
