# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20161125_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
