# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20161125_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
