# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20161126_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_proveedor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_mat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rif', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
                ('tlf1', models.CharField(max_length=15)),
                ('tlf2', models.CharField(blank=True, max_length=15)),
                ('dire', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='c_proveedores',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='c_proveedores',
            name='codigo_mat',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='C_proveedores',
        ),
        migrations.AddField(
            model_name='material_proveedor',
            name='codigo_prove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='material_proveedor',
            unique_together=set([('codigo_prove', 'codigo_mat')]),
        ),
    ]
