# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20161205_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='atencion_e',
            field=models.EmailField(default='prueba@prueba.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='atencion_n',
            field=models.CharField(default='prueba', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cond_ent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cond_g',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cond_p',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicio_presupuesto',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
