# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20161216_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='cond_ent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='cond_g',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='cond_p',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
