# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20161216_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='estatus',
            field=models.CharField(choices=[('Preventa', 'Preventa'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Preventa', max_length=10),
        ),
    ]
