# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_presupuesto_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='cond_ent',
        ),
    ]
