# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_presupuesto_cond_ent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa_rechazo',
            name='codigo_pro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
    ]
