# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20161229_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='repuesta',
            new_name='respuesta',
        ),
    ]
