# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20161229_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='codigo_pro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Proyecto'),
        ),
    ]
