# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20161229_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Ejecucion', 'Ejecucion'), ('Problemas', 'Problemas'), ('Culminado', 'Culminado')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='f_est',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='f_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='f_ini',
            field=models.DateField(blank=True, null=True),
        ),
    ]
