# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20170106_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
