# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20170106_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='codigo_rd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Reporte_detalle'),
        ),
    ]
