# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20170106_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte_detalle',
            name='nombre_t',
            field=models.CharField(default='hola', max_length=60),
            preserve_default=False,
        ),
    ]
