# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20170107_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='2017-01-06'),
            preserve_default=False,
        ),
    ]
