# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_reporte_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
