# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_reporte_leido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa_tecnico_movimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ci_tecnico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador')),
                ('codigo_eta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Etapa')),
                ('codigo_mov', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movimiento')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together=set([('codigo_eta', 'nro')]),
        ),
    ]
