# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20170112_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Retorno', 'Retorno'), ('Egreso', 'Egreso')], max_length=10),
        ),
    ]
