# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20170112_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
