# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_movimiento_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='ci_almace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Trabajador'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='codigo_ne',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='codigo_oc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='persona_e',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='persona_t',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='proveedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
