# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20170113_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa_tecnico_movimiento',
            unique_together=set([('codigo_mov', 'ci_tecnico', 'codigo_eta')]),
        ),
    ]
