# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20170117_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='rif_prove',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='codigo_ne',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='codigo_oc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
