# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20170118_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='rif_prove',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Proveedor'),
        ),
    ]
