# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_movimiento_rif_prove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Ejecucion', 'Ejecucion'), ('Culminado', 'Culminado')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(choices=[('Nueva', 'Nueva'), ('Procesada', 'Procesada'), ('Atendida', 'Atendida')], default='n', max_length=1),
        ),
    ]
