# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20170124_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(choices=[('Nueva', 'Nueva'), ('Procesada', 'Procesada'), ('Atendida', 'Atendida')], default='Nueva', max_length=10),
        ),
    ]
