# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20170124_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cond_contrib',
            field=models.CharField(blank=True, choices=[('Ordinario', 'Ordinario'), ('Especial', 'Especial'), ('Formales', 'Formales')], max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cond_pago',
            field=models.CharField(choices=[('Credito', 'Credito'), ('Debito', 'Debito'), ('Efectivo', 'Efectivo')], max_length=10),
        ),
    ]
