# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20170124_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_servicio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('codigo_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Reporte')),
                ('codigo_ser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Servicio')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='etapa_servicio',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='etapa_servicio',
            name='codigo_eta',
        ),
        migrations.RemoveField(
            model_name='etapa_servicio',
            name='codigo_ser',
        ),
        migrations.DeleteModel(
            name='Etapa_servicio',
        ),
        migrations.AlterUniqueTogether(
            name='reporte_servicio',
            unique_together=set([('codigo_ser', 'codigo_rep')]),
        ),
    ]
