# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20170201_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='codigo_eta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Etapa'),
        ),
    ]
