# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20170201_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='f_vis',
        ),
        migrations.AddField(
            model_name='reporte_inicial',
            name='f_vis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='banco_dest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reporte_inicial',
            name='cargo_a',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
