# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20170208_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(decimal_places=4, default=200.0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporte_detalle',
            name='cargo_a',
            field=models.CharField(max_length=60),
        ),
    ]
