# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20170214_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(blank=True),
        ),
    ]
