# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20170215_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
