# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_solicitud_f_vis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='estatus',
            field=models.CharField(choices=[('Preventa', 'Preventa'), ('Aprobado', 'Aprobado'), ('Cerrado', 'Cerrado'), ('Rechazado', 'Rechazado')], default='Preventa', max_length=10),
        ),
    ]
